### ISSUE TITLE
How about display seconds?

### ISSUE THREAD

**Issue by projct1** [eddyerburgh/vue-digital-clock#2]
With flashing colon?)

**Comment by eddyerburgh** [comment]
Sure, I'll add it sometime. Maybe tomorrow lunchtime

**Comment by projct1** [comment]
👌

**Comment by eddyerburgh** [comment]
It's been added in v1.4.0 👍

**Comment by projct1** [comment]
Yea, fine, thanks, looks good 👍
But, how about **display** seconds?)

**Comment by eddyerburgh** [comment]
Added to 1.5.0

**Comment by rorc** [comment]
Hmm, why seconds so fast?) For each display and hide comma 😄

**Comment by projct1** [comment]
Ok, thanks dude 👍
