### ISSUE TITLE
Cannot use setTimeout in tests

### ISSUE THREAD

**Issue by cat5inthecradle** [eddyerburgh/vue-digital-clock#3]
Hey, I found your repo looking for an Avoriaz example that needed tests to wait for vue updates.

The solution you've got in your tests using setTimeout does not work. For example, if you add:

`setTimeout(() => expect(false).to.be.true, 1000);`

to one of your tests, the test will still pass.

**Comment by eddyerburgh** [comment]
Hey, thanks.

I've fixed the async tests.

You can call [`wrapper.update()`](https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/update.html) to  update the Vue component.
